/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.36
 * Generated at: 2022-11-11 03:29:16 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.time.LocalDate;
import java.util.LinkedList;
import entities.Alquileres.Alquiler;

public final class AdministrarAlquiler_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.time.LocalDate");
    _jspx_imports_classes.add("entities.Alquileres.Alquiler");
    _jspx_imports_classes.add("java.util.LinkedList");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			"/Error.jsp", true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("\t<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\n");
      out.write("    <meta charset=\"utf-8\">\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n");
      out.write("    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->\n");
      out.write("    <meta name=\"description\" content=\"\">\n");
      out.write("    <meta name=\"author\" content=\"\">\n");
      out.write("\t<title>Administrar Alquileres</title>\n");
      out.write("\t\t\n");
      out.write("\t");

		LinkedList<Alquiler> alquileres = request.getAttribute("ListaAlquileres") != null ? (LinkedList<Alquiler>)request.getAttribute("ListaAlquileres") : new LinkedList<Alquiler>();
		Alquiler alquilerSeleccionado = (Alquiler)request.getAttribute("AlquilerSeleccionado");
	
      out.write("\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "WEB-INF/Navegacion.html", out, false);
      out.write("\n");
      out.write("\t\n");
      out.write("\t<div class=\"card\" style=\"margin: 12px;\">\n");
      out.write("\t\t<h5 class=\"card-header\" style=\"backgroud-color: aliceblue;\">\n");
      out.write("\t\t\tAlquileres registrados\n");
      out.write("\t\t</h5>\n");
      out.write("\t\t<div class=\"card-body\">\n");
      out.write("\t\t\t<div class=\"col-md-6\">\n");
      out.write("\t\t\t\t<div class=\"text-danger\">\n");
      out.write("\t\t\t\t\t");
      out.print((String)request.getAttribute("ErrorMessage") != null ? (String)request.getAttribute("ErrorMessage") : "");
      out.write("\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t\t<form class=\"form\" action=\"AdministrarAlquiler\" method=\"post\">\n");
      out.write("\t\t\t\n");
      out.write("\t\t\t<!-- SECCION DE ALTA Y MODIFICACION  -->\n");
      out.write("\t\t\t<div class=\"card\" style=\"margin: 12px;\">\n");
      out.write("\t\t\t\t<div class=\"card-header\">\n");
      out.write("\t\t\t\t\t<a data-toggle=\"collapse\" data-target=\"#Filtros\" style=\"text-decoration: none;\">Filtros</a>\n");
      out.write("\t\t\t\t\t<a data-toggle=\"collapse\" data-target=\"#Filtros\" class=\"pull-right\" style=\"text-decoration: none;\">\n");
      out.write("\t\t\t\t\t\t<i class=\"fa fa-arrow-down pr-2\"></i>\n");
      out.write("\t\t\t\t\t</a>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t\t<div class=\"collapse-in\" id=\"Filtros\">\n");
      out.write("\t\t\t\t\t<div class=\"card-body\">\n");
      out.write("\t\t\t\t\t\t<p class=\"card-title\">Filtrar alquileres</p>\n");
      out.write("\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\t<div class=\"form-group\">\n");
      out.write("\t\t\t\t\t\t\t<div class=\"form-row\">\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"input-group mb-3\">\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"input-group-prepend\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<span class=\"input-group-text\" id=\"TextFechaInicio\">Fecha Inicio</span>\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t<input type=\"date\" class=\"form-control\" id=\"inputFechaInicio\" name=\"FechaInicio\" value=\"");
      out.print(LocalDate.now());
      out.write("\">\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"input-group-prepend\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<span class=\"input-group-text\" id=\"TextFechaFin\">Fecha Fin</span>\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t<input type=\"date\" class=\"form-control\" id=\"inputFechaFin\" name=\"FechaFin\" value=\"");
      out.print(LocalDate.now());
      out.write("\">\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"input-group-prepend\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<span class=\"input-group-text\" id=\"TextEstadoAlquiler\">Estado</span>\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "WEB-INF/ComboEstadosAlquiler.jsp", out, false);
      out.write("\n");
      out.write("\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\t\t<div class=\"form-row\">\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"input-group mb-3\">\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"input-group-prepend\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<span class=\"input-group-text\" id=\"SelectFormaPago\">Forma Pago</span>\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "WEB-INF/ComboFormasPago.jsp", out, false);
      out.write("\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"input-group-prepend\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<span class=\"input-group-text\" id=\"SelectTipoAlquiler\">Tipo Alquiler</span>\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "WEB-INF/ComboTiposAlquileres.jsp", out, false);
      out.write("\n");
      out.write("\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\t\t<div class=\"form-row\">\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"col-lg-11\">\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"pull-right\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<button class=\"btn btn-primary\" type=\"submit\" name=\"Buscar\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<i class=\"fa fa-search pr-2\"></i>Buscar\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</button>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<button class=\"btn btn-secondary\" type=\"submit\" name=\"Cancelar\" >\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<i class=\"fa fa-remove pr-2\"></i>Cancelar\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</button>\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t\t<!--  FIN ALTA Y MODIFICACION  -->\n");
      out.write("\t\t\t</form>\n");
      out.write("\t\t\t<form action=\"AdministrarAlquiler\" method=\"post\">\n");
      out.write("\t\t\t<!--  SECCION DE GRILLA  -->\n");
      out.write("\t\t\t<div class=\"card\" style=\"margin: 12px;\">\n");
      out.write("\t\t\t\t<div class=\"card-body\">\n");
      out.write("\t\t\t\t\t<h5 class=\"card-title\">Registrados</h5>\n");
      out.write("\t\t\t\t\t\n");
      out.write("\t\t\t\t\t<button class=\"btn btn-primary pull-right\" type=\"submit\" name=\"Agregar\">\n");
      out.write("\t\t\t\t\t\t<i class=\"fa fa-plus pr-2\"></i>Agregar\n");
      out.write("\t\t\t\t\t</button>\n");
      out.write("\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\n");
      out.write("\t\t\t\t\t<div class=\"row\">\n");
      out.write("\t\t\t            \t<div class=\"col-12 col-sm-12 col-lg-12\">\n");
      out.write("\t\t\t                \t<div class=\"table-responsive\">\n");
      out.write("\t\t                    \t\t<table class=\"table\">\n");
      out.write("\t\t\t                    \t\t<thead>\n");
      out.write("\t\t\t                    \t\t\t<tr>\n");
      out.write("\t\t\t                    \t\t\t\t<th>ID</th>\n");
      out.write("\t\t\t                    \t\t    \t<th>Fecha Hora Inicio</th>\n");
      out.write("\t\t\t                    \t\t    \t<th>Fecha Hora Fin</th>\n");
      out.write("\t\t\t                    \t\t    \t<th>Pagado</th>\n");
      out.write("\t\t\t                    \t\t    \t<th>Forma Pago</th>\n");
      out.write("\t\t\t                    \t\t    \t<th>Tipo Alquiler</th>\n");
      out.write("\t\t\t                    \t\t    \t<th>Patente</th>\n");
      out.write("\t\t\t                    \t\t    \t<th>Precio Pactado</th>\n");
      out.write("\t\t\t                    \t\t    \t<th>Precio Final</th>\n");
      out.write("\t\t\t                    \t\t    \t<th>Nro. Cochera</th>\n");
      out.write("\t\t\t                    \t\t    \t<th>Empleado</th>\n");
      out.write("\t\t\t                    \t\t    \t<th></th>\n");
      out.write("\t\t\t                    \t\t    \t<th></th>\n");
      out.write("\t\t\t                      \t\t\t</tr>\n");
      out.write("\t\t\t                      \t\t</thead>\n");
      out.write("\t\t\t                    \t\t<tbody>\n");
      out.write("\t\t\t                    \t\t");
 for (Alquiler alquiler: alquileres) { 
      out.write("\n");
      out.write("\t\t\t                    \t\t\t<tr>\n");
      out.write("\t\t\t                    \t\t\t\t<td>");
      out.print(alquiler.getID());
      out.write("</td>\n");
      out.write("\t\t\t                    \t\t\t\t<td>");
      out.print(alquiler.getFechaHoraInicio().toString());
      out.write("</td>\n");
      out.write("\t\t\t                    \t\t\t\t<td>");
      out.print(alquiler.getFechaHoraFin().toString());
      out.write("</td>\n");
      out.write("\t\t\t                    \t\t\t\t<td><input type=\"checkbox\" ");
      out.print(alquiler.isPagado() ? "checked='checked'" : "");
      out.write(" disabled></td>\n");
      out.write("\t\t\t                    \t\t\t\t<td>");
      out.print(alquiler.getFormaPago().getDescripcion());
      out.write("</td>\n");
      out.write("\t\t\t                    \t\t\t\t<td>");
      out.print(alquiler.getTipoAlquiler().getDescripcion());
      out.write("</td>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<td>");
      out.print(alquiler.getVehiculo().getPatente());
      out.write("</td>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<td>");
      out.print(alquiler.getPrecio());
      out.write("</td>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<td>");
      out.print(alquiler.getTotalPrecio());
      out.write("</td>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<td>");
      out.print(alquiler.getCochera().getNroCochera());
      out.write("</td>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<td>");
      out.print(alquiler.getEmpleado().toString());
      out.write("</td>\n");
      out.write("\t\t\t                    \t\t\t\t<td>\n");
      out.write("\t\t\t                    \t\t\t\t\t<button class=\"btn btn-link-custom\" type=\"submit\"  name=\"ModificarID\" value=\"");
      out.print(alquiler.getID());
      out.write("\">\n");
      out.write("\t\t\t                    \t\t\t\t\t\t<i class=\"fa fa-pencil pr-2\"></i>\n");
      out.write("\t\t\t                    \t\t\t\t\t</button>\n");
      out.write("\t\t\t                    \t\t\t\t\t<button class=\"btn btn-link\" style=\"color: #dd4b39;\" type=\"submit\" name=\"EliminarID\" value=\"");
      out.print(alquiler.getID() );
      out.write('"');
      out.write(' ');
      out.print(alquiler.isPagado() ? "disabled" : "enabled" );
      out.write(">\n");
      out.write("\t\t\t                    \t\t\t\t\t\t<i class=\"fa fa-trash pr-2\"></i>\n");
      out.write("\t\t\t                    \t\t\t\t\t</button>\n");
      out.write("\t\t\t                    \t\t\t\t</td>\n");
      out.write("\t\t\t                    \t\t\t\t<td>\n");
      out.write("\t\t\t                    \t\t\t\t\t<button class=\"btn btn-link-custom\" type=\"submit\"  name=\"PagarID\" value=\"");
      out.print(alquiler.getID());
      out.write("\">\n");
      out.write("\t\t\t                    \t\t\t\t\t\t<i class=\"fa fa-credit-card pr-2\"></i>Pagar\n");
      out.write("\t\t\t                    \t\t\t\t\t</button>\n");
      out.write("\t\t\t                    \t\t\t\t</td>\n");
      out.write("\t\t\t                    \t\t\t</tr>\n");
      out.write("\t\t\t                    \t\t");
 } 
      out.write("\n");
      out.write("\t\t                    \t\t</tbody>\n");
      out.write("\t\t                   \t\t</table>\n");
      out.write("\t\t               \t\t</div>\n");
      out.write("\t\t          \t\t</div>\t\n");
      out.write("\t\t          \t</div>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t\t<!--  FIN DE GRILLA  -->\n");
      out.write("\t\t\t</form>\n");
      out.write("\n");
      out.write("\n");
      out.write("\t\t\t\n");
      out.write("\t\t</div>\n");
      out.write("\t</div>\n");
      out.write("\t\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
