/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.36
 * Generated at: 2022-11-13 16:00:03 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.LinkedList;
import entities.Vehiculos.TipoVehiculo;

public final class AdministrarTipoVehiculo_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("entities.Vehiculos.TipoVehiculo");
    _jspx_imports_classes.add("java.util.LinkedList");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("\t<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\n");
      out.write("    <meta charset=\"utf-8\">\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n");
      out.write("    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->\n");
      out.write("    <meta name=\"description\" content=\"\">\n");
      out.write("    <meta name=\"author\" content=\"\">\n");
      out.write("\t<title>Administrar Tipo Vehiculo</title>\n");
      out.write("\t\t\n");
      out.write("\t");

		LinkedList<TipoVehiculo> tiposVehiculo = request.getAttribute("ListaTiposVehiculo") != null ? (LinkedList<TipoVehiculo>)request.getAttribute("ListaTiposVehiculo") : new LinkedList<TipoVehiculo>();
		TipoVehiculo vehiculoSeleccionado = (TipoVehiculo)request.getAttribute("VehiculoSeleccionado");
	
      out.write("\n");
      out.write("\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "WEB-INF/Navegacion.jsp", out, false);
      out.write("\n");
      out.write("\t\n");
      out.write("\t<div class=\"card\" style=\"margin: 12px;\">\n");
      out.write("\t\t<h5 class=\"card-header\" style=\"backgroud-color: aliceblue;\">\n");
      out.write("\t\t\tTipos de Vehiculos\n");
      out.write("\t\t</h5>\n");
      out.write("\t\t<div class=\"card-body\">\n");
      out.write("\t\t\t<div class=\"col-md-6\">\n");
      out.write("\t\t\t\t<div class=\"text-danger\">\n");
      out.write("\t\t\t\t\t");
      out.print((String)request.getAttribute("ErrorMessage") != null ? (String)request.getAttribute("ErrorMessage") : "");
      out.write("\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t\t<form class=\"form\" action=\"AdministrarTipoVehiculo\" method=\"post\">\n");
      out.write("\t\t\t\n");
      out.write("\t\t\t<!-- SECCION DE ALTA Y MODIFICACION  -->\n");
      out.write("\t\t\t<div class=\"card\" style=\"margin: 12px;\">\n");
      out.write("\t\t\t\t<div class=\"card-header\">\n");
      out.write("\t\t\t\t\t<a data-toggle=\"collapse\" data-target=\"#Detalle\" style=\"text-decoration: none;\">Detalle</a>\n");
      out.write("\t\t\t\t\t<a data-toggle=\"collapse\" data-target=\"#Detalle\" class=\"pull-right\" style=\"text-decoration: none;\">\n");
      out.write("\t\t\t\t\t\t<i class=\"fa fa-plus pr-2\"></i>\n");
      out.write("\t\t\t\t\t</a>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t\t<div class=\"");
      out.print(vehiculoSeleccionado != null ? "" : "collapse" );
      out.write("\" id=\"Detalle\">\n");
      out.write("\t\t\t\t\t<div class=\"card-body\">\n");
      out.write("\t\t\t\t\t\t<p class=\"card-title\">Tipo de Vehiculo</p>\n");
      out.write("\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\t<div class=\"form-group\">\n");
      out.write("\t\t\t\t\t\t\t<div class=\"form-row\">\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"input-group mb-3\">\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"input-group-prepend\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<span class=\"input-group-text\" id=\"TextoDescripcion\">Descripcion</span>\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t<input type=\"hidden\" class=\"form-control\" id=\"inputID\" name=\"ID\" value=\"");
      out.print(vehiculoSeleccionado != null ? vehiculoSeleccionado.getID() : 0);
      out.write("\">\n");
      out.write("\t\t\t\t\t\t\t\t\t<input type=\"text\" class=\"form-control\" id=\"inputDescripcion\" name=\"Descripcion\" placeholder=\"Ingrese Descripcion\" required=\"\" autofocus=\"\" value=\"");
      out.print(vehiculoSeleccionado != null ? vehiculoSeleccionado.getDescripcion() : "");
      out.write("\">\n");
      out.write("\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\t\t<div class=\"form-row\">\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"col-lg-11\">\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"pull-right\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<button class=\"btn btn-primary\" type=\"submit\" name=\"");
      out.print(vehiculoSeleccionado != null ? "Modificar" : "Guardar");
      out.write("\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<i class=\"fa fa-save pr-2\"></i>Guardar\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</button>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<button class=\"btn btn-secondary\" onclick=\"");
 vehiculoSeleccionado = null;
      out.write("\" type=\"submit\" data-toggle=\"collapse\" data-target=\"#Detalle\" >\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<i class=\"fa fa-remove pr-2\"></i>Cancelar\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</button>\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t\t<!--  FIN ALTA Y MODIFICACION  -->\n");
      out.write("\t\t\t</form>\n");
      out.write("\t\t\t<form action=\"AdministrarTipoVehiculo\" method=\"post\">\n");
      out.write("\t\t\t<!--  SECCION DE GRILLA  -->\n");
      out.write("\t\t\t<div class=\"card\" style=\"margin: 12px;\">\n");
      out.write("\t\t\t\t<div class=\"card-body\">\n");
      out.write("\t\t\t\t\t<h5 class=\"card-title\">Registrados</h5>\n");
      out.write("\t\t\t\t\t\n");
      out.write("\t\t\t\t\t<div class=\"row\">\n");
      out.write("\t\t\t            \t<div class=\"col-12 col-sm-12 col-lg-12\">\n");
      out.write("\t\t\t                \t<div class=\"table-responsive\">\n");
      out.write("\t\t                    \t\t<table class=\"table\">\n");
      out.write("\t\t\t                    \t\t<thead>\n");
      out.write("\t\t\t                    \t\t\t<tr>\n");
      out.write("\t\t\t                    \t\t\t\t<th>ID</th>\n");
      out.write("\t\t\t                    \t\t    \t<th>Tipo</th>\n");
      out.write("\t\t\t                    \t\t    \t<th></th>\n");
      out.write("\t\t\t                      \t\t\t</tr>\n");
      out.write("\t\t\t                      \t\t</thead>\n");
      out.write("\t\t\t                    \t\t<tbody>\n");
      out.write("\t\t\t                    \t\t");
 for (TipoVehiculo tipoVehiculo: tiposVehiculo) { 
      out.write("\n");
      out.write("\t\t\t                    \t\t\t<tr>\n");
      out.write("\t\t\t                    \t\t\t\t<td>");
      out.print(tipoVehiculo.getID());
      out.write("</td>\n");
      out.write("\t\t\t                    \t\t\t\t<td>");
      out.print(tipoVehiculo.getDescripcion());
      out.write("</td>\n");
      out.write("\t\t\t                    \t\t\t\t<td>\n");
      out.write("\t\t\t                    \t\t\t\t\t<button class=\"btn btn-link-custom\" type=\"submit\"  name=\"BuscarID\" value=\"");
      out.print(tipoVehiculo.getID());
      out.write("\">\n");
      out.write("\t\t\t                    \t\t\t\t\t\t<i class=\"fa fa-pencil pr-2\"></i>\n");
      out.write("\t\t\t                    \t\t\t\t\t</button>\n");
      out.write("\t\t\t                    \t\t\t\t\t<button class=\"btn btn-link\" style=\"color: #dd4b39;\" type=\"submit\" name=\"Eliminar\" value=\"");
      out.print(tipoVehiculo.getID() );
      out.write("\">\n");
      out.write("\t\t\t                    \t\t\t\t\t\t<i class=\"fa fa-trash pr-2\"></i>\n");
      out.write("\t\t\t                    \t\t\t\t\t</button>\n");
      out.write("\t\t\t                    \t\t\t\t</td>\n");
      out.write("\t\t\t                    \t\t\t</tr>\n");
      out.write("\t\t\t                    \t\t");
 } 
      out.write("\n");
      out.write("\t\t                    \t\t</tbody>\n");
      out.write("\t\t                   \t\t</table>\n");
      out.write("\t\t               \t\t</div>\n");
      out.write("\t\t          \t\t</div>\t\n");
      out.write("\t\t          \t</div>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t\t<!--  FIN DE GRILLA  -->\n");
      out.write("\t\t\t</form>\n");
      out.write("\n");
      out.write("\n");
      out.write("\t\t\t\n");
      out.write("\t\t</div>\n");
      out.write("\t</div>\n");
      out.write("\n");
      out.write("\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
