/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.36
 * Generated at: 2022-11-13 15:33:29 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class Index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta charset=\"ISO-8859-1\">\n");
      out.write("<title>Park-IT</title>\n");
      out.write("</head>\n");
      out.write("\n");
      out.write("<body>\n");
      out.write("\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "WEB-INF/Navegacion.jsp", out, false);
      out.write("\n");
      out.write("</body>\n");
      out.write("\n");
      out.write("<form action=\"MenuPrincipal\" method=\"post\">\n");
      out.write("\n");
      out.write("\t<!-- CARD DE ESTACIONAMIENTO  -->\n");
      out.write("\t<div class=\"card\" style=\"margin: 12px;\">\n");
      out.write("\t\t<div class=\"card-header\">\n");
      out.write("\t\t\t<a data-toggle=\"collapse\" data-target=\"#SeccionEstacionamiento\"\n");
      out.write("\t\t\t\tstyle=\"text-decoration: none;\">Estacionamiento</a>\n");
      out.write("\t\t</div>\n");
      out.write("\n");
      out.write("\t\t<!-- INICIO SECCION ESTACIONAMIENTO -->\n");
      out.write("\t\t<div class=\"collapse-in\" id=\"SeccionEstacionamiento\">\n");
      out.write("\t\t\t<div class=\"card-body\">\n");
      out.write("\t\t\t\t<div class=\"row\">\n");
      out.write("\t\t\t\t\n");
      out.write("\t\t\t\t\t<!--  INICIO TIPOS DE VEHICULOS  -->\n");
      out.write("\t\t\t\t\t<div class=\"col-auto\">\n");
      out.write("\t\t\t\t\t\t<div class=\"card\" style=\"width: 18rem;\">\n");
      out.write("\t\t\t\t\t\t\t<div class=\"card-body\">\n");
      out.write("\t\t\t\t\t\t\t\t<h5 class=\"card-title\">Tipos de Vehiculos</h5>\n");
      out.write("\t\t\t\t\t\t\t\t<h6 class=\"card-subtitle mb-2 text-muted\">Alta, Baja o\n");
      out.write("\t\t\t\t\t\t\t\t\tModificación</h6>\n");
      out.write("\t\t\t\t\t\t\t\t<p class=\"card-text\">Accede al menú para visualizar,\n");
      out.write("\t\t\t\t\t\t\t\t\tmodificar o eliminar los tipos de vehiculos admitidos por el\n");
      out.write("\t\t\t\t\t\t\t\t\testacionamiento.</p>\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"pull-right\">\n");
      out.write("\t\t\t\t\t\t\t\t\t<button class=\"btn btn-link\" type=\"submit\" name=\"Accion\"\n");
      out.write("\t\t\t\t\t\t\t\t\t\tvalue=\"AdministrarTipoVehiculo\">Ir a</button>\n");
      out.write("\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t<!--  FIN TIPOS DE VEHICULOS -->\n");
      out.write("\t\t\t\t\t\n");
      out.write("\t\t\t\t\t<!--  INICIO SERVICIOS  -->\n");
      out.write("\t\t\t\t\t<div class=\"col-auto\">\n");
      out.write("\t\t\t\t\t\t<div class=\"card\" style=\"width: 18rem;\">\n");
      out.write("\t\t\t\t\t\t\t<div class=\"card-body\">\n");
      out.write("\t\t\t\t\t\t\t\t<h5 class=\"card-title\">Tipos de Servicios</h5>\n");
      out.write("\t\t\t\t\t\t\t\t<h6 class=\"card-subtitle mb-2 text-muted\">Alta, Baja o\n");
      out.write("\t\t\t\t\t\t\t\t\tModificación</h6>\n");
      out.write("\t\t\t\t\t\t\t\t<p class=\"card-text\">Accede al menú para visualizar,\n");
      out.write("\t\t\t\t\t\t\t\t\tmodificar o eliminar los tipos de servicios ofrecidos por el\n");
      out.write("\t\t\t\t\t\t\t\t\testacionamiento.</p>\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"pull-right\">\n");
      out.write("\t\t\t\t\t\t\t\t\t<button class=\"btn btn-link\" type=\"submit\" name=\"Accion\"\n");
      out.write("\t\t\t\t\t\t\t\t\t\tvalue=\"AdministrarServicio\">Ir a</button>\n");
      out.write("\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t<!--  FIN SERVICIOS -->\n");
      out.write("\t\t\t\t\t\n");
      out.write("\t\t\t\t\t<!--  INICIO TIPOS DE COCHERAS  -->\n");
      out.write("\t\t\t\t\t<div class=\"col-auto\">\n");
      out.write("\t\t\t\t\t\t<div class=\"card\" style=\"width: 18rem;\">\n");
      out.write("\t\t\t\t\t\t\t<div class=\"card-body\">\n");
      out.write("\t\t\t\t\t\t\t\t<h5 class=\"card-title\">Tipos de Cocheras</h5>\n");
      out.write("\t\t\t\t\t\t\t\t<h6 class=\"card-subtitle mb-2 text-muted\">Alta, Baja o\n");
      out.write("\t\t\t\t\t\t\t\t\tModificación</h6>\n");
      out.write("\t\t\t\t\t\t\t\t<p class=\"card-text\">Accede al menú para visualizar,\n");
      out.write("\t\t\t\t\t\t\t\t\tmodificar o eliminar los tipos de cocheras admitidos por el\n");
      out.write("\t\t\t\t\t\t\t\t\testacionamiento.</p>\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"pull-right\">\n");
      out.write("\t\t\t\t\t\t\t\t\t<button class=\"btn btn-link\" type=\"submit\" name=\"Accion\"\n");
      out.write("\t\t\t\t\t\t\t\t\t\tvalue=\"AdministrarTipoCochera\">Ir a</button>\n");
      out.write("\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t<!--  FIN TIPOS DE COCHERAS  -->\n");
      out.write("\t\t\t\t\t\n");
      out.write("\t\t\t\t\t<!--  INICIO TIPOS DE ALQUILERES  -->\n");
      out.write("\t\t\t\t\t<div class=\"col-auto\">\n");
      out.write("\t\t\t\t\t\t<div class=\"card\" style=\"width: 18rem;\">\n");
      out.write("\t\t\t\t\t\t\t<div class=\"card-body\">\n");
      out.write("\t\t\t\t\t\t\t\t<h5 class=\"card-title\">Tipos de Alquileres</h5>\n");
      out.write("\t\t\t\t\t\t\t\t<h6 class=\"card-subtitle mb-2 text-muted\">Alta, Baja o\n");
      out.write("\t\t\t\t\t\t\t\t\tModificación</h6>\n");
      out.write("\t\t\t\t\t\t\t\t<p class=\"card-text\">Accede al menú para visualizar,\n");
      out.write("\t\t\t\t\t\t\t\t\tmodificar o eliminar los tipos de alquileres admitidos por el\n");
      out.write("\t\t\t\t\t\t\t\t\testacionamiento.</p>\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"pull-right\">\n");
      out.write("\t\t\t\t\t\t\t\t\t<button class=\"btn btn-link\" type=\"submit\" name=\"Accion\"\n");
      out.write("\t\t\t\t\t\t\t\t\t\tvalue=\"AdministrarTipoAlquiler\">Ir a</button>\n");
      out.write("\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t<!--  FIN TIPOS DE ALQUILERES  -->\n");
      out.write("\t\t\t\t\t\n");
      out.write("\t\t\t\t\t<!--  INICIO PRECIOS DE ALQUILERES  -->\n");
      out.write("\t\t\t\t\t<div class=\"col-auto\">\n");
      out.write("\t\t\t\t\t\t<div class=\"card\" style=\"width: 18rem;\">\n");
      out.write("\t\t\t\t\t\t\t<div class=\"card-body\">\n");
      out.write("\t\t\t\t\t\t\t\t<h5 class=\"card-title\">Precios</h5>\n");
      out.write("\t\t\t\t\t\t\t\t<h6 class=\"card-subtitle mb-2 text-muted\">Alta, Baja o\n");
      out.write("\t\t\t\t\t\t\t\t\tModificación</h6>\n");
      out.write("\t\t\t\t\t\t\t\t<p class=\"card-text\">Accede al menú para visualizar,\n");
      out.write("\t\t\t\t\t\t\t\t\tmodificar o eliminar los precios de alquileres vigentes en el\n");
      out.write("\t\t\t\t\t\t\t\t\testacionamiento.</p>\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"pull-right\">\n");
      out.write("\t\t\t\t\t\t\t\t\t<button class=\"btn btn-link\" type=\"submit\" name=\"Accion\"\n");
      out.write("\t\t\t\t\t\t\t\t\t\tvalue=\"AdministrarPrecioAlquiler\">Ir a</button>\n");
      out.write("\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t<!--  FIN PRECIOS DE ALQUILERES  -->\n");
      out.write("\n");
      out.write("\t\t\t\t\t<!--  INICIO TIPOS DE FORMAS DE PAGO  --> \n");
      out.write("\t\t\t\t\t<div class=\"col-auto\"> \n");
      out.write("\t\t\t\t\t\t<div class=\"card\" style=\"width: 18rem;\"> \n");
      out.write("\t\t\t\t\t\t\t<div class=\"card-body\"> \n");
      out.write("\t\t\t\t\t\t\t\t<h5 class=\"card-title\">Tipos de Formas de Pago</h5> \n");
      out.write("\t\t\t\t\t\t\t\t<h6 class=\"card-subtitle mb-2 text-muted\">Alta, Baja o \n");
      out.write("\t\t\t\t\t\t\t\t\tModificación</h6> \n");
      out.write("\t\t\t\t\t\t\t\t<p class=\"card-text\">Accede al menú para visualizar, \n");
      out.write("\t\t\t\t\t\t\t\t\tmodificar o eliminar los tipos de formas de pago admitidos por el \n");
      out.write("\t\t\t\t\t\t\t\t\testacionamiento.</p> \n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"pull-right\"> \n");
      out.write("\t\t\t\t\t\t\t\t\t<button class=\"btn btn-link\" type=\"submit\" name=\"Accion\" \n");
      out.write("\t\t\t\t\t\t\t\t\t\tvalue=\"AdministrarFormaPago\">Ir a</button> \n");
      out.write("\t\t\t\t\t\t\t\t</div> \n");
      out.write("\t\t\t\t\t\t\t</div> \n");
      out.write("\t\t\t\t\t\t</div> \n");
      out.write("\t\t\t\t\t</div> \n");
      out.write("\t\t\t\t\t<!--  FIN TIPOS DE TIPOS DE FORMAS DE PAGO --> \n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</div>\n");
      out.write("\t\t<!--  FIN SECCION ESTACIONAMIENTO -->\n");
      out.write("\t</div>\n");
      out.write("\t\n");
      out.write("\t<!-- CARD DE USUARIOS -->\n");
      out.write("\t<div class=\"card\" style=\"margin: 12px;\">\n");
      out.write("\t\t<div class=\"card-header\">\n");
      out.write("\t\t\t<a data-toggle=\"collapse\" data-target=\"#SeccionUsuarios\"\n");
      out.write("\t\t\t\tstyle=\"text-decoration: none;\">Usuarios</a>\n");
      out.write("\t\t</div>\n");
      out.write("\n");
      out.write("\t<!--  INICIO SECCION USUARIOS -->\n");
      out.write("\t\t<div class=\"collapse\" id=\"SeccionUsuarios\">\n");
      out.write("\t\t\t<div class=\"card-body\">\n");
      out.write("\t\t\t\t<div class=\"row\">\n");
      out.write("\t\t\t\t\n");
      out.write("\t\t\t\t\t<!--  INICIO EMPLEADOS  -->\n");
      out.write("\t\t\t\t\t<div class=\"col-auto\">\n");
      out.write("\t\t\t\t\t\t<div class=\"card\" style=\"width: 18rem;\">\n");
      out.write("\t\t\t\t\t\t\t<div class=\"card-body\">\n");
      out.write("\t\t\t\t\t\t\t\t<h5 class=\"card-title\">Empleados</h5>\n");
      out.write("\t\t\t\t\t\t\t\t<h6 class=\"card-subtitle mb-2 text-muted\">Alta, Baja o\n");
      out.write("\t\t\t\t\t\t\t\t\tModificación</h6>\n");
      out.write("\t\t\t\t\t\t\t\t<p class=\"card-text\">Accede al menú para visualizar,\n");
      out.write("\t\t\t\t\t\t\t\t\tmodificar o eliminar los empleados del lugar. A la vez, \n");
      out.write("\t\t\t\t\t\t\t\t\tasignar o modificar usuarios correspondientes.</p>\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"pull-right\">\n");
      out.write("\t\t\t\t\t\t\t\t\t<button class=\"btn btn-link\" type=\"submit\" name=\"Accion\"\n");
      out.write("\t\t\t\t\t\t\t\t\t\tvalue=\"Empleado\">Ir a</button>\n");
      out.write("\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t<!--  FIN EMPLEADOS -->\n");
      out.write("\t\t\t\t\t\n");
      out.write("\t\t\t\t\t<!--  INICIO CLIENTES  -->\n");
      out.write("\t\t\t\t\t<div class=\"col-auto\">\n");
      out.write("\t\t\t\t\t\t<div class=\"card\" style=\"width: 18rem;\">\n");
      out.write("\t\t\t\t\t\t\t<div class=\"card-body\">\n");
      out.write("\t\t\t\t\t\t\t\t<h5 class=\"card-title\">Clientes</h5>\n");
      out.write("\t\t\t\t\t\t\t\t<h6 class=\"card-subtitle mb-2 text-muted\">Alta, Baja o\n");
      out.write("\t\t\t\t\t\t\t\t\tModificación</h6>\n");
      out.write("\t\t\t\t\t\t\t\t<p class=\"card-text\">Accede al menú para visualizar,\n");
      out.write("\t\t\t\t\t\t\t\t\tmodificar o eliminar los clientes del lugar. A la vez, \n");
      out.write("\t\t\t\t\t\t\t\t\tasignar o modificar usuarios correspondientes.</p>\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"pull-right\">\n");
      out.write("\t\t\t\t\t\t\t\t\t<button class=\"btn btn-link\" type=\"submit\" name=\"Accion\"\n");
      out.write("\t\t\t\t\t\t\t\t\t\tvalue=\"Cliente\">Ir a</button>\n");
      out.write("\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t<!--  FIN CLIENTES -->\n");
      out.write("\t\t\t\t\t\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</div>\n");
      out.write("\t</div>\n");
      out.write("\n");
      out.write("</form>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
